# Generated by Django 5.2.4 on 2025-07-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unlock_at', models.IntegerField(help_text='Number of clicks required to unlock')),
                ('speed', models.FloatField(default=0, help_text='Auto-clicker speed per second')),
                ('click_multiplier', models.FloatField(default=1.0, help_text='Click multiplier bonus')),
                ('icon', models.CharField(default='🏆', help_text='Emoji icon for achievement', max_length=10)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic')], default='common', max_length=20)),
                ('theme_primary', models.CharField(default='from-blue-400 to-blue-600', max_length=100)),
                ('theme_secondary', models.CharField(default='blue-500', max_length=50)),
                ('theme_accent', models.CharField(default='blue-400', max_length=50)),
                ('theme_background', models.CharField(default='blue-900', max_length=50)),
                ('theme_bg_class', models.CharField(default='bg-blue-950', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this achievement is active in the game')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'ordering': ['order', 'unlock_at'],
            },
        ),
    ]
